name: Test Build Process

on:
  push:
    branches: ["main", "dev"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Verify output directory
        run: |
          if [ -d "out" ]; then
            echo "✅ Build successful - 'out' directory exists"
            ls -la out/
          else
            echo "❌ Build failed - 'out' directory not found"
            exit 1
          fi 